<template>
  <div class="legal page">
    <header class="rail">
      <router-link to="/" class="brand-mark">
        <span class="dot"></span>
        <span class="brand-text">SWARMIE</span>
      </router-link>
      <span class="rail-context">/ terms</span>
      <router-link to="/" class="rail-far">← home</router-link>
    </header>

    <main class="doc">
      <h1 class="doc-title h-display">Terms of Service</h1>
      <p class="doc-meta">Last Updated: June 1, 2026</p>

      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Swarmie ("the Service"), you agree to be bound by these Terms of Service and our <router-link to="/privacy">Privacy Policy</router-link>. If you do not agree, you may not use the Service.</p>
      </section>

      <section>
        <h2>2. About Swarmie</h2>
        <p>Swarmie is an AI-powered founder intelligence and decision stress-testing platform. The Service uses synthetic AI personas and analytical systems to surface potential objections, questions, risks, and opportunities relating to startup ideas, pitches, launches, positioning, fundraising, and related business decisions.</p>
        <p>Swarmie is intended as a thinking aid and decision-support tool only.</p>
      </section>

      <section>
        <h2>3. AI Generated Content Disclaimer</h2>
        <p>All reports, reactions, verdicts, recommendations, simulations, scores, analyses, and outputs generated by Swarmie are produced by artificial intelligence systems.</p>
        <p>The outputs:</p>
        <ul>
          <li>Are not produced by real customers, investors, founders, or communities.</li>
          <li>Are not predictions of future outcomes.</li>
          <li>May be inaccurate, incomplete, misleading, outdated, or biased.</li>
          <li>Should not be treated as factual, professional, legal, investment, financial, accounting, tax, medical, or business advice.</li>
        </ul>
        <p>You remain solely responsible for all decisions and actions taken based on the Service.</p>
      </section>

      <section>
        <h2>4. No Reliance</h2>
        <p>You acknowledge that startup, fundraising, product, marketing, hiring, pricing, launch, investment, and business decisions involve uncertainty.</p>
        <p>You agree not to rely exclusively on Swarmie outputs when making important decisions and acknowledge that independent verification is required.</p>
      </section>

      <section>
        <h2>5. Experimental Service</h2>
        <p>Swarmie is an evolving and experimental technology platform.</p>
        <p>Features, outputs, models, methodologies, pricing, availability, and functionality may change, be suspended, or be discontinued at any time without notice.</p>
      </section>

      <section>
        <h2>6. Your Content</h2>
        <p>You retain ownership of all content you submit to the Service.</p>
        <p>By submitting content, you grant us a worldwide, non-exclusive, royalty-free license to host, process, transmit, analyze, reproduce, and use that content solely for:</p>
        <ul>
          <li>Providing the Service.</li>
          <li>Operating and maintaining the platform.</li>
          <li>Improving the Service.</li>
          <li>Security and abuse prevention.</li>
          <li>Creating aggregated or anonymized analytics.</li>
        </ul>
        <p>We do not claim ownership of your content.</p>
        <p>You represent and warrant that:</p>
        <ul>
          <li>You have the right to submit the content.</li>
          <li>The content does not infringe any third-party rights.</li>
          <li>The content does not violate applicable law.</li>
          <li>The content does not contain information you are prohibited from sharing.</li>
        </ul>
      </section>

      <section>
        <h2>7. Confidential Information</h2>
        <p>You should not submit confidential information, trade secrets, customer records, credentials, access tokens, proprietary source code, investor materials, acquisition plans, or information you are not authorized to disclose.</p>
        <p>While we take reasonable measures to protect submitted information, Swarmie is not intended to function as a secure data room, legal repository, or confidential document storage system.</p>
      </section>

      <section>
        <h2>8. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Violate any law or regulation.</li>
          <li>Infringe intellectual property rights.</li>
          <li>Upload malicious code.</li>
          <li>Attempt unauthorized access to the Service.</li>
          <li>Reverse engineer the platform.</li>
          <li>Interfere with platform operation.</li>
          <li>Submit unlawful, abusive, fraudulent, or harmful content.</li>
          <li>Use the Service to generate harmful, deceptive, or illegal material.</li>
        </ul>
      </section>

      <section>
        <h2>9. Third Party Providers</h2>
        <p>The Service relies on third-party infrastructure, AI providers, analytics services, hosting providers, and databases.</p>
        <p>We are not responsible for interruptions, errors, outages, or actions caused by third-party providers beyond our reasonable control.</p>
      </section>

      <section>
        <h2>10. Intellectual Property</h2>
        <p>Except for user-submitted content, all rights, title, and interest in the Service, including software, branding, designs, interfaces, and documentation, remain the property of the Service operator.</p>
        <p>No rights are granted except as expressly stated in these Terms.</p>
      </section>

      <section>
        <h2>11. Disclaimer of Warranties</h2>
        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE."</p>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, NON-INFRINGEMENT, AND AVAILABILITY.</p>
        <p>WE DO NOT WARRANT THAT THE SERVICE WILL BE ERROR-FREE, SECURE, OR UNINTERRUPTED.</p>
      </section>

      <section>
        <h2>12. Limitation of Liability</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.</p>
        <p>WE SHALL NOT BE LIABLE FOR BUSINESS LOSSES, LOST PROFITS, LOST DATA, LOST REVENUE, LOST OPPORTUNITIES, OR DECISIONS MADE IN RELIANCE ON THE SERVICE.</p>
        <p>OUR TOTAL LIABILITY SHALL NOT EXCEED THE GREATER OF:</p>
        <ul>
          <li>USD $100</li>
          <li>OR THE AMOUNT PAID BY YOU TO THE SERVICE DURING THE PRECEDING TWELVE MONTHS</li>
        </ul>
      </section>

      <section>
        <h2>13. Indemnification</h2>
        <p>You agree to defend, indemnify, and hold harmless the Service operator from claims, liabilities, damages, losses, and expenses arising from:</p>
        <ul>
          <li>Your use of the Service.</li>
          <li>Your submitted content.</li>
          <li>Your violation of these Terms.</li>
          <li>Your violation of applicable laws or third-party rights.</li>
        </ul>
      </section>

      <section>
        <h2>14. Termination</h2>
        <p>We may suspend, restrict, or terminate access to the Service at any time for any reason, including suspected abuse, security concerns, legal compliance, or violations of these Terms.</p>
      </section>

      <section>
        <h2>15. Changes to These Terms</h2>
        <p>We may modify these Terms at any time.</p>
        <p>Updated versions will be posted with a revised "Last Updated" date.</p>
        <p>Continued use of the Service after updates constitutes acceptance of the revised Terms.</p>
      </section>

      <section>
        <h2>16. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of India.</p>
        <p>Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in Ahmedabad, Gujarat, India.</p>
      </section>

      <section>
        <h2>17. Contact</h2>
        <p>For questions regarding these Terms:</p>
        <p>Email: <a href="mailto:hpatadi07@gmail.com">hpatadi07@gmail.com</a></p>
      </section>
    </main>
  </div>
</template>

<script setup>
// static legal page
</script>

<style scoped>
.legal { color: var(--ink); background: var(--paper); min-height: 100vh; }
.rail {
  display: flex; align-items: center; gap: var(--space-4);
  padding: var(--space-3) var(--space-6); border-bottom: 1px solid var(--rule);
}
.brand-mark { display: inline-flex; align-items: center; gap: var(--space-2); font-family: var(--font-mono); font-size: var(--text-xs); font-weight: 600; letter-spacing: 0.22em; }
.brand-mark .dot { width: 8px; height: 8px; border-radius: 50%; background: var(--accent); box-shadow: 0 0 14px var(--accent); }
.rail-context { font-family: var(--font-mono); font-size: var(--text-xs); letter-spacing: 0.08em; color: var(--ink-2); }
.rail-far { margin-left: auto; font-family: var(--font-mono); font-size: var(--text-xs); color: var(--ink-2); }
.rail-far:hover { color: var(--ink); }

.doc { max-width: 720px; margin: 0 auto; padding: var(--space-7) var(--space-6) var(--space-9); }
.doc-title { font-size: clamp(32px, 6vw, 52px); font-weight: 500; margin: 0 0 var(--space-2); }
.doc-meta { font-family: var(--font-mono); font-size: var(--text-xs); color: var(--ink-3); margin: 0 0 var(--space-5); }
.doc section { margin-bottom: var(--space-5); }
.doc h2 { font-family: var(--font-mono); font-size: var(--text-sm); letter-spacing: 0.08em; text-transform: uppercase; color: var(--ink); margin: 0 0 var(--space-2); }
.doc p, .doc li { font-family: var(--font-body); font-size: var(--text-sm); line-height: 1.6; color: var(--ink-2); }
.doc p { margin: 0 0 var(--space-2); }
.doc ul { margin: var(--space-2) 0; padding-left: var(--space-5); display: flex; flex-direction: column; gap: 6px; }
.doc a { color: var(--accent-bright); text-decoration: underline; text-underline-offset: 2px; }
.doc a:hover { color: var(--accent); }
</style>
